### ISSUE TITLE
{{if foo}} when foo is not passed as an argument - Rendering fails

### ISSUE THREAD

**Issue by mavdi** [coolony/kiwi#6]
When not passing a variable to the render function, say

response.render("index", {});

and when using {{if foo}} in the template

the template fails to render. I think in such cases foo should just default to false.

**Comment by pierreis** [comment]
The way variable handling is implemented today makes this difficult, but I'll look further into this issue.
However, you can disable strict mode with `var template = new Kiwi.template({ strict: false })`, which should achieve the result you are expecting.

Your second best option would be to use `{{if __data.foo}}`.

My best advice, however, would be to always define every variable you are using in your templates, in order to avoid side-effects and unexpected results.

**Comment by mavdi** [comment]
Thanks! __data.foo works great. 

It might be a lack of understanding from my side, basically I want to load a certain css on admin page only. So this is what I am doing:
<code>
{{if __data.admin}}
                <link href='/assets/css/admin.css' rel='stylesheet' type='text/css'>
{{/if}}
</code>

Problem being that I don't want to send {admin : false} in every other page I want to render. Is this the right way of doing it you think?

**Comment by pierreis** [comment]
Are you using Express?
If yes, you probably should have a look at Express locals.

For example, in your main script:

```
app.locals.admin = false;
```

This done, you have the admin variable defaulting to false in every template you are rendering through Express. You then just have to override this for your admin pages.

**Comment by mavdi** [comment]
Thank you very much for your time Pierre,

Works like a charm, much appriciated.
